replaced config args with config file

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,43 +1,30 @@
 #!/usr/bin/env bash
 
-PYTHON_BOOLEAN=false
-DOCKER_BOOLEAN=false
+set -e
+set -u 
+set -o pipefail
 
-while getopts 'pd' OPTION; do
-    case "$OPTION" in
-        p)
-            PYTHON_BOOLEAN=true
-        ;;
-        d)
-            DOCKER_BOOLEAN=true
-        ;;
-        ?)
-            echo -e "\e[31m./$(basename $0) [-p (python aliases)] [-d (docker aliases)] /project/dir \e[0m" >&2
-            exit 1
-        ;;
-    esac
-done
-
-shift "$(($OPTIND -1))"
-
-if [ ! -d "$1" ]; then
-    echo -e "\e[31mProject Directory does not exist. \e[0m"
-else
-    sed -e "s~INSERT_BASE_DIR~${PWD}~"        \
-        -e "s~INSERT_PROJECT_DIR~${1}~"                 \
-        -e "s~INSERT_PYTHON_BOOLEAN~${PYTHON_BOOLEAN}~" \
-        -e "s~INSERT_DOCKER_BOOLEAN~${DOCKER_BOOLEAN}~" \
-        bashrc_template > .bashrc
-
-    mv .bashrc ~
-
-    if [ "$PYTHON_BOOLEAN" == true ]; then
-        echo -e "\e[32mPython aliases enabled. \e[0m"
-    fi
-
-    if [ "$DOCKER_BOOLEAN" == true ]; then
-        echo -e "\e[32mDocker aliases enabled. \e[0m"
-    fi
-
-    echo -e "\e[32mUpdated .bashrc, restart terminal to load changes. \e[0m"
+echo ">> Checking configs file <<"
+if [ ! -f "./configs" ]; then
+    echo "No configs file found, creating..."
+    cp configs_template configs
+    vi configs
 fi
+
+source ./configs
+
+if [ ! -d "$WORK_DIR" ]; then
+    echo "ERROR: Work Directory ($WORK_DIR) does not exist."
+    exit 1
+fi
+
+echo "Work Dir: $WORK_DIR"
+echo "Docker:   $HAS_DOCKER"
+echo "Python:   $HAS_PYTHON"
+
+echo ">> Creating .bashrc <<"
+sed -e "s~INSERT_BASE_DIR~${PWD}~" bashrc_template > ~/.bashrc
+
+echo "Load .bashrc using \"source ~/.bashrc\" or by restarting terminal."
+
+exit 0
diff --git a/scripts/np b/scripts/np
--- a/scripts/np
+++ b/scripts/np
@@ -1,22 +1,53 @@
 #!/usr/bin/env bash
 
-# creates a new project from an existing project by copying 
-# the project directory and deleting the .git directory.
+set -e
+set -u 
+set -o pipefail
 
-if [ -z "$2" ]; then
-    echo -e "\e[31mInvalid format \e[0m"
-    echo -e "\e[33mnp [source] [destination] \e[0m"
-elif [ ! -d "$1" ]; then
-    echo -e "\e[31mSource directory does not exist. \e[0m"
-elif [ -d "$2" ]; then
-    echo -e "\e[31mDestination directory already exists. \e[0m"
-else
-    echo -e "\e[32mCopying project. \e[0m"
-    cp $1 $2 -r
-    cd $2
+usage () {
+    echo "Copies source directory to a new directory and removes .git from new location."
+    echo "  np [source] [destination]"
+}
 
-    if [ -d ".git" ]; then
-        echo -e "\e[32mRemoving git fron new project. \e[0m"
-        rm -rf .git
-    fi
+# options
+while getopts ":h" opt; do
+    case "$opt" in
+        h)
+            usage
+            exit 0
+            ;;
+        ?)
+            echo "ERROR: Invalid flag"
+            exit 1
+            ;;
+    esac
+done
+
+# errors
+if [ -z "${2+x}" ]; then
+    echo "ERROR: Missing arguments."
+    exit 1
 fi
+
+if [ ! -d "$1" ]; then
+    echo "ERROR: Source directory does not exist."
+    exit 1
+fi
+
+if [ -d "$2" ]; then
+    echo "ERROR: Destination directory already exists."
+    exit 1
+fi
+
+#exec
+echo "Copying $1 to $2..."
+cp $1 $2 -r
+cd $2
+
+if [ -d ".git" ]; then
+    echo "Removing .git from $2..."
+    rm -rf .git
+fi
+
+echo "Done."
+exit 0
